services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    container_name: grasa_backend
    ports:
      - "8000:8000"
    networks:
      - grasa_net
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: grasa_frontend
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: "http://backend:8000"
    depends_on:
      - backend
    networks:
      - grasa_net
    restart: always

networks:
  grasa_net:
    driver: bridge










